- hosts: web
  remote_user: nicolas
  become: true
  gather_facts: False

  tasks:
  - name: install python 3
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python3-minimal)

- hosts: base
  roles:
    - mysql

- hosts: web

  roles:
    - server
    - php
    - wordpress
    - ftp
